[features]
seeds = false
[programs.localnet]
excrow = "6cn9ZD4tPQjyo1iSaBqcuuCFnPhLj6naTCAtqkKKRmht"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/walterphillips/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
